### ISSUE TITLE
Swiperの修正

### ISSUE THREAD

**Issue by pss-aileen** [pss-aileen/practice-bootstrap5-food-delivery#25]
- [x] 矢印の色を変える

**Comment by pss-aileen** [comment]
https://stackoverflow.com/questions/72545107/swiper-version-8-2-2-cant-change-the-button-colors-react
普通のCSSが適応されないなぜ？

**Comment by pss-aileen** [comment]
https://swiperjs.com/element#parts

これ！

```scss
 swiper-container::part(button-prev),
  swiper-container::part(button-next) {
    color: $primary;
  }
```

これでスタイル適応される
